# config.yaml
command: likwid-mpirun  # likwid-mpirun or likwid-perfctr
likwid-mpirun:
  options:
    - -g: MEM_DP        # Measure over the MEM_DP group
    - -nperdomain: S:36 # 36 cores/socket
    - -stats            # Print likwid statistics
    - -O                # Output tables in csv format
    - -marker           # activate likwid marker API
    - hpcmd_suspend     # suspend the HPCMD daemon 
