repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed.
        args: ["--maxkb=500"]     
      - id: check-merge-conflict    # Check for files that contain merge conflict strings.
      - id: check-toml              # Attempts to load all TOML files to verify syntax.
      - id: check-yaml              # Attempts to load all yaml files to verify syntax.