repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the latest stable version
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=500"]  # Example to check file size
      - id: check-merge-conflict  # Checks for unresolved merge conflicts in files
      - id: check-toml  # Checks if .toml files have valid syntax
  # - repo: https://github.com/pre-commit/mirrors-autopep8
  #   rev: v2.0.4  # Use the latest stable version of autopep8
  #   hooks:
  #     - id: autopep8
  #       args: ["--in-place", "--max-line-length", "120", "-aa", "--ignore=E221,E226,E203,E731,E711"]
  #       # E201/E202 – Whitespace after/before (, [ or {
  #       # E226 – Missing whitespace around arithmetic operators
  #       # E266 – Too many leading # for block comment
  #       # E731 – Do not assign a lambda expression
  #       # E203 – Whitespace before : (used in slicing)
  #       # E711 - Ignore enforcing 'is not None' over '!= None'
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Use the latest stable version of black
    hooks:
      - id: black
        args: ["--line-length", "120"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Use the latest stable version of isort
    hooks:
      - id: isort
        args: ["--profile", "black"]
  # - repo: https://github.com/pre-commit/mirrors-pylint
  #   rev: v3.0.0a5  # or the latest stable version
  #   hooks:
  #     - id: pylint
  #       name: pylint-docstring-check
  #       args: ["--disable=all", "--enable=C0199"]
  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 5.0.2  # Use the latest stable version of Flake8
  #   hooks:
  #     - id: flake8
  #       args: ["--max-line-length", "120"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.12.0  # Use the latest stable version of mypy
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports"]

# Global exclude pattern for all hooks
exclude: '.*[kK]ernel[s]?.*\.py$'