repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest stable version
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed.
        args: ["--maxkb=1000"]     
      - id: check-merge-conflict    # Check for files that contain merge conflict strings.
      - id: check-toml              # Attempts to load all TOML files to verify syntax.
      - id: check-yaml              # Attempts to load all yaml files to verify syntax.
        args: ["--unsafe"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout # remove jupyter notebook cell output
