name: MacOS

on:
  schedule:
    # run at 1 a.m. on Sunday
    - cron: "0 1 * * 0" 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-latest-build:
    uses: ./.github/workflows/reusable-testing.yml
    with:
      os: macos-latest