# name: MacOS
on:
  push:
    branches:
      - main
      - devel-clean
  pull_request:
    branches:
      - main
      - devel-clean

# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  macos-latest-build:
    uses: ./.github/workflows/hello_world_reusable_wf.yml
    with:
      os: macos-latest