name: Publish Struphy to test-PyPI

on:
  push:

# .github/workflows/ci-cd.yml
jobs:
  pypi-publish:
    name: Upload release to test-PyPI

    runs-on: ubuntu-latest

    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build the package
      run: python -m build

    - name: Publish package distributions to test-PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/project/struphy-test-3

    # - name: Publish to test-PyPI
    #   env:
    #     TWINE_USERNAME: __token__ # Use API token
    #     TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #   # run: twine upload dist/*
    #   run: twine upload --repository testpypi dist/*
# jobs:
#   build-and-publish:
#     runs-on: ubuntu-latest

#     steps:s



