name: PR - domain cloning in Container

on:
  pull_request:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  model-tests-in-container-with-struphy:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/struphy-hub/struphy/ubuntu-with-struphy:latest
      credentials:
        username: spossann
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check .testmondata 1
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Setup cache for testmon
        uses: actions/cache@v4
        with:
          path: |
            .testmondata-clones
          key: testmon-clones-${{ github.event.number }}-${{ github.run_number }}
          restore-keys: |
            testmon-clones-${{ github.event.number }}-
            testmon-clones-

      - name: Check .testmondata 2
        run: |
          ls .testmon* || echo "No .testmondata"

      # This step can be removed when the updated ghcr images are pushed
      - name: Install sqlite
        shell: bash
        run: apt install -y sqlite3

      - name: Install Struphy in Container
        uses: ./.github/actions/install/struphy_in_container

      - name: Compile Struphy
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy compile

      - name: Verification tests with 4 MPI
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-clones
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test verification --mpi 4

      - name: Verification tests with clones
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-clones
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test verification --mpi 4 --nclones 2