name: PR - unit tests in Container

on:
  pull_request:
    branches:
      - devel
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  unit-tests-in-container-with-struphy:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/struphy-hub/struphy/ubuntu-with-struphy:latest
      credentials:
        username: spossann
        password: ${{ secrets.GHCR_TOKEN }}

    env:
      TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-unit

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup cache for testmon
        uses: actions/cache@v4
        with:
          path: .testmondata-unit
          key: testmon-unit-${{ github.event.number }}-${{ github.run_number }}
          restore-keys: |
            testmon-unit-${{ github.event.number }}-
            testmon-unit-

      - name: Check .testmondata
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Install sqlite
        shell: bash
        run: apt install -y sqlite3

      - name: Install Struphy in Container
        uses: ./.github/actions/install/struphy_in_container

      - name: Compile Struphy
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy compile

      - name: Run unit tests
        shell: bash
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy compile --status
          pip show mpi4py
          pip uninstall -y mpi4py
          struphy test unit

      # - name: Run unit tests with MPI
      #   shell: bash
      #   run: |
      #     source /struphy_c_/env_c_/bin/activate
      #     pip install -U mpi4py
      #     struphy test unit --mpi 2

      - name: Upload .testmondata as cache for later tests
        uses: actions/cache/save@v4
        with:
          path: .testmondata-unit
          key: testmon-unit-${{ github.event.number }}-${{ github.run_number }}