name: PR - unit tests in Container

on:
  pull_request:
    branches:
      - main
      - devel
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

# concurrency:
#   group: "pages"
#   cancel-in-progress: false

jobs:
  unit-tests-in-container-with-struphy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/struphy-hub/struphy/ubuntu-with-struphy:latest
      credentials:
        username: spossann
        password: ${{ secrets.GHCR_TOKEN }}
    steps:

      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Struphy in Container
        uses: ./.github/actions/install/struphy_in_container

      - name: Compile Struphy
        run: |
          which python3
          source /struphy_c_/env_c_/bin/activate
          which python3
          struphy compile --status
          struphy compile

      - name: Run unit tests
        shell: bash
        run: |
          which python3
          source /struphy_c_/env_c_/bin/activate
          which python3
          echo $FC
          echo $CC
          echo $CXX
          export FC=`which gfortran` 
          export CC=`which gcc`
          export CXX=`which g++`  
          echo $FC
          echo $CC
          echo $CXX
          struphy compile --status
          struphy --refresh-models
          pip show mpi4py
          pip uninstall -y mpi4py
          pip list
          struphy test unit

      - name: Run unit tests with MPI
        shell: bash
        run: |
          which python3
          source /struphy_c_/env_c_/bin/activate
          which python3
          echo $FC
          echo $CC
          echo $CXX
          export FC=`which gfortran` 
          export CC=`which gcc`
          export CXX=`which g++`  
          echo $FC
          echo $CC
          echo $CXX
          pip install -U mpi4py
          struphy compile --status
          struphy --refresh-models
          struphy test unit --mpi 2

      
