name: PR - pure Python tests in Container

on:
  pull_request:
    branches:
      - devel
  push:
    branches:
      - devel
  schedule:
    # run at 1 a.m. on Sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  model-tests-in-container-with-reqs:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/struphy-hub/struphy/ubuntu-with-reqs:latest
      credentials:
        username: spossann
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check .testmondata 1
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Setup cache for testmon
        uses: actions/cache@v4
        with:
          path: |
            .testmondata-pure-python
            .testmondata-pure-python-mpi
          key: testmon-pure-python-${{ github.ref_name }}-${{ github.event.number }}-${{ github.run_number }}
          restore-keys: |
            testmon-pure-python-${{ github.ref_name }}-${{ github.event.number }}-
            testmon-pure-python-${{ github.ref_name }}
            testmon-pure-python-devel
            testmon-pure-python-

      - name: Check .testmondata 2
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Install Struphy
        shell: bash
        run: |
          python3 -m venv env
          source env/bin/activate
          pip install .[dev]

      - name: LinearMHD test
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python
        run: |
          source env/bin/activate
          struphy compile --status
          struphy test LinearMHD

      - name: Vlasov test
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python
        run: |
          source env/bin/activate
          struphy test Vlasov

      - name: GuidingCenter test
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python
        run: |
          source env/bin/activate
          struphy test GuidingCenter

      - name: VlasovAmpere test
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python
        run: |
          source env/bin/activate
          struphy test VlasovAmpereOneSpecies

      - name: EulerSPH test
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python
        run: |
          source env/bin/activate
          struphy test EulerSPH

      - name: Vlasov test MPI
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python-mpi
        # init .testmondata with non-MPI call
        run: |
          source env/bin/activate
          struphy test Maxwell
          struphy test Vlasov --mpi 2

      - name: GuidingCenter test MPI
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python-mpi
        run: |
          source env/bin/activate
          struphy test GuidingCenter --mpi 2

      - name: VlasovAmpere test MPI
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python-mpi
        run: |
          source env/bin/activate
          struphy test VlasovAmpereOneSpecies --mpi 2

      - name: EulerSPH test MPI
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-pure-python-mpi
        run: |
          source env/bin/activate
          struphy test EulerSPH --mpi 2
