name: PR - model tests in Container

on:
  pull_request:
    branches:
      - devel
  push:
    branches:
      - devel
  schedule:
    # run at 1 a.m. on Sunday
    - cron: "0 1 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  model-tests-in-container-with-struphy:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/struphy-hub/struphy/ubuntu-with-struphy:latest
      credentials:
        username: spossann
        password: ${{ secrets.GHCR_TOKEN }}

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check .testmondata 1
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Setup cache for testmon
        uses: actions/cache@v4
        with:
          path: |
            .testmondata-model
            .testmondata-model-mpi
          key: testmon-model-${{ github.ref_name }}-${{ github.event.number }}-${{ github.run_number }}
          restore-keys: |
            testmon-model-${{ github.ref_name }}-${{ github.event.number }}-
            testmon-model-${{ github.ref_name }}
            testmon-model-devel
            testmon-model-

      - name: Check .testmondata 2
        run: |
          ls .testmon* || echo "No .testmondata"

      - name: Install Struphy in Container
        uses: ./.github/actions/install/struphy_in_container

      - name: Compile Struphy
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy compile

      - name: LinearMHD test
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-model
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test LinearMHD

      - name: Toy test
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-model
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test toy

      - name: Model tests
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-model
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test models 

      - name: Verification tests
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-model
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test verification

      - name: Model tests with MPI
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-model-mpi
        # init .testmondata with non-MPI call
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test Maxwell
          struphy test models --mpi 2

      - name: Verification tests with 2 MPI
        shell: bash
        env:
          TESTMON_DATAFILE: ${{ github.workspace }}/.testmondata-model-mpi
        run: |
          source /struphy_c_/env_c_/bin/activate
          struphy test verification --mpi 2