name: Ubuntu

on:
  schedule:
    # run at 1 a.m. on Sunday
    - cron: "0 1 * * 0" 
  workflow_dispatch:

jobs:
  ubuntu-install-test:
    uses: ./.github/workflows/reusable-testing.yml
    with:
      os: ubuntu-latest